config/routes.rb
Rails.application.routes.draw do
  constraints(Constraints::BackofficeSubdomain) do
    scope module: :backoffice, as: :backoffice, subdomain: :backoffice do
      root to: 'dashboards#show'
      get '/', to: 'dashboards#show', as: 'dashboard'
      post '/set_moderator/:id', to: 'users#set_moderator', as: 'set_moderator'
      resources :users, except: [:destroy]
      resources :clubs, except: [:destroy]
    end

    get :sign_in, to: 'sessions#new'
    post :sign_in, to: 'sessions#create'
    get :sign_out, to: 'sessions#destroy'
  end

  get :find_club, to: 'home#find_club'
  post :find_club, to: 'home#list_clubs'

  root to: 'home#index'

  get :branding, to: 'branding#index' if Rails.env.development?
end

app/controllers/backoffice/application_controller.rb
module Backoffice
  class ApplicationController < ActionController::Base
    layout 'backoffice'
    include Concerns::Authentication

    protect_from_forgery with: :exception

    before_action :authenticate!
  end
end

app/controllers/backoffice/clubs_controller.rb
module Backoffice
  class ClubsController < ApplicationController
    before_action :find_club, only: %i(show edit update destroy)

    before_action :new_club, only: %i(new create)

    def index
      @clubs = Club.all
    end

    def new
    end

    def create
      @club.assign_attributes(club_params.merge(created_by: current_user.id))
      if @club.save
        redirect_to backoffice_club_path(@club.id)
      else
        render :new
      end
    end

    def show
    end

    def destroy
      @club.destroy
    end

    def edit
    end

    def update
      redirect_to backoffice_club_path(@club.id) if @club.update_attributes(club_params)
    end

    private

    def club_params
      params.require(:club).permit(:name, :subdomain, :about)
    end

    def find_club
      @club = Club.find(params[:id])
    end

    def new_club
      @club = Club.new
    end
  end
end

app/controllers/backoffice/dashboards_controller.rb
module Backoffice
  class DashboardsController < ApplicationController
    def show
    end
  end
end

app/controllers/backoffice/users_controller.rb
module Backoffice
  class UsersController < ApplicationController
    before_action :find_club, only: %i(destroy edit set_moderator show update)

    before_action :new_user, only: %i(create new)

    def index
      @club_list = Club.all.each_with_object({}) { |club, hash| hash[club.id] = club.subdomain }
      @users = params[:filter].present? ? User.club_ids(params[:filter]) : User.all
    end

    def new
    end

    def create
      @user.update_attributes(user_params.merge(role: :admin))
      if @user.save
        redirect_to action: 'show', id: @user.id
      else
        render :new
      end
    end

    def show
    end

    def edit
    end

    def destroy
      @user.destroy
    end

    def set_moderator
      redirect_to action: 'index' if @user.update_attributes(role: :moderator)
    end

    def update
      redirect_to action: 'show', id: @user.id if @user.update_attributes(user_params)
    end

    private

    def find_user
      @user = User.find(params[:id])
    end

    def new_user
      @user = User.new
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :club_id, :password)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_date(date)
    date&.strftime('%m/%d/%Y')
  end

  def format_datetime(date)
    date&.strftime('%e %B at %l %P')
  end

  def checked(name)
    params[:filter].present? && params[:filter].include?(name.to_s)
  end

  def get_avatar(photo)
    photo.exists? ? photo.url : 'profile-icon.png'
  end

  def number_of_available_user_notifications(club, user)
    club.notifications.where.not(creator: user).count
  end
end

app/views/backoffice/clubs/edit.html.haml
.col-sm-12.profile-main.tab-content
  #general.colform.tab-pane.active{ role: 'tabpanel' }
    .column-title= "#{t('helpers.forms.edit')} #{@club.name}"
  = branded_form_for @club, url: backoffice_club_path(@club) do |f|
    = render partial: 'backoffice/clubs/partials/form', locals: { f: f }

app/views/backoffice/clubs/index.html.haml
.breadcrumb
  =link_to t('backoffice.backoffice_title'), root_path
  %i.fa.fa-long-arrow-right{ 'aria-hidden': true }
  %strong= t('backoffice.clubs')
.row
  .col-sm-12.profile-main.tab-content
    #general.colform.tab-pane.active{ role: 'tabpanel' }
      .form-title-with-button
        = t('backoffice.clubs')
        = link_to t('backoffice.create_new_club'), new_backoffice_club_path, class: 'btn btn-primary pull-right'
      %table.data-table.table.table-striped.table-bordered
        %thead
          %tr
            %th= t('backoffice.club_page.club_id')
            %th= t('backoffice.club_page.club_name')
            %th= t('backoffice.subdomain')
            %th= t('backoffice.club_page.users')
            %th= t('backoffice.club_page.created_by')
            %th= t('backoffice.club_page.created_at')
            %th
        %tbody
          - @clubs.each do |club|
            %tr
              %td= club.id
              %td= link_to club.name, backoffice_club_path(club)
              %td= club.subdomain
              %td= club.users.count
              %td= User.find(club.created_by).name if club.created_by.present?
              %td= club.created_at.strftime('%y/%m/%d at %I:%M%p')
              %td
                = link_to 'Edit club', edit_backoffice_club_path(club)
        %tfoot
          %tr
            %th= t('backoffice.club_page.club_id')
            %th= t('backoffice.club_page.club_name')
            %th= t('backoffice.subdomain')
            %th= t('backoffice.club_page.users')
            %th= t('backoffice.club_page.created_by')
            %th= t('backoffice.club_page.created_at')
            %th

app/views/backoffice/clubs/new.html.haml
.col-sm-12.profile-main.tab-content
  #general.colform.tab-pane.active{ role: 'tabpanel' }
    .column-title= t('backoffice.create_new_club')
  = branded_form_for @club, url: backoffice_clubs_path, html: { method: :post } do |f|
    = render partial: 'backoffice/clubs/partials/form', locals: { f: f }

app/views/backoffice/clubs/partials/_form.html.haml
= f.input :name
= f.input :subdomain
= f.input :about

= f.submit t"helpers.forms.#{action_name}"

app/views/backoffice/clubs/show.html.haml
.col-sm-12.profile-main.tab-content
  #general.colform.tab-pane.active{ role: 'tabpanel' }
    .column-title= "Club #{@club.name}"
    %table.table.table-striped
      %tr
        %th= t('backoffice.name')
        %td= @club.name
      %tr
        %th= t('backoffice.subdomain')
        %td= @club.subdomain
      %tr
        %th= t('backoffice.about')
        %td= @club.about

    =link_to 'Edit', edit_backoffice_club_path(@club), class: 'btn btn-primary pull-right'

app/views/backoffice/dashboards/partials/_left_menu.html.haml
.column-title Dashboard
%ul.nav.nav-tabs.button-list
  %li{ class: 'active' }
    = link_to t('backoffice.general'), backoffice_dashboard_path, class: 'btn btn-block btn-link'
  %li
    = link_to t('backoffice.clubs'), backoffice_clubs_path, class: 'btn btn-block btn-link'
  %li
    = link_to t('backoffice.users'), backoffice_users_path, class: 'btn btn-block btn-link'

app/views/backoffice/dashboards/show.html.haml
.breadcrumb
  =link_to 'Backoffice', backoffice_dashboard_path
  %i.fa.fa-long-arrow-right{ 'aria-hidden': true }
  %strong Dashboard
.row
  .col-sm-4.side-menu-left-menu.profile-side
    = render partial: 'backoffice/dashboards/partials/left_menu'
  .col-sm-8
    .column-title
      = t('backoffice.general')
    .discussion-placehold
      = t('backoffice.dashdoard_welcome')

app/views/backoffice/users/edit.html.haml
.col-sm-12.profile-main.tab-content
  #general.colform.tab-pane.active{ role: 'tabpanel' }
    .column-title= "Edit #{@user.name}"
  = branded_form_for @user, url: backoffice_user_path(@user) do |f|
    = render partial: 'backoffice/users/partials/form', locals: { f: f }

app/views/backoffice/users/index.html.haml
.breadcrumb
  =link_to 'Backoffice', backoffice_dashboard_path
  %i.fa.fa-long-arrow-right{ 'aria-hidden': true }
  %strong= t('backoffice.users')
.row
  .col-sm-2.side-menu-left-menu.profile-side
    = render partial: 'backoffice/users/partials/sidebar'
  .col-sm-10.profile-main.tab-content
    #general
      .form-title-with-button
        = t('backoffice.users')
        = link_to t('backoffice.create_new_admin'), new_backoffice_user_path, class: 'btn btn-primary pull-right'
      %table.data-table.table.table-striped.table-bordered
        %thead
          %tr
            %th= t('backoffice.name')
            %th= t('backoffice.email')
            %th= t('backoffice.club_subdomain')
            %th= t('backoffice.role')
            %th= t('backoffice.last_login_at')
            %th
        %tbody
          - @users.each do |user|
            %tr
              %td= link_to user.name, backoffice_user_path(user)
              %td= user.email
              %td= user.club&.subdomain
              %td= user.role
              %td= user.last_login_at&.strftime('%y/%m/%d at %I:%M%p')
              %td
                - if user.role != 'moderator' && user.club.present?
                  = link_to t('backoffice.set_as_moderator'), backoffice_set_moderator_path(user), method: :post, data: { confirm: 'Are you sure?'}
        %tfoot
          %tr
            %th= t('backoffice.name')
            %th= t('backoffice.email')
            %th= t('backoffice.club_subdomain')
            %th= t('backoffice.role')
            %th= t('backoffice.last_login_at')
            %th

app/views/backoffice/users/new.html.haml
.col-sm-12.profile-main.tab-content
  #general.colform.tab-pane.active{ role: 'tabpanel' }
    .column-title= t('backoffice.create_new_user')
  = branded_form_for @user, url: backoffice_users_path do |f|
    = render partial: 'backoffice/users/partials/form', locals: { f: f }

app/views/backoffice/users/partials/_form.html.haml
= f.input :first_name
= f.input :last_name
= f.input :email
= f.password :password

= f.submit t"helpers.forms.#{action_name}"

app/views/backoffice/users/partials/_sidebar.html.haml
.side-menu-left-menu
  = form_tag(backoffice_users_path, id: 'users_filter', method: :get) do
    .form-title-with-button Filter by Club
    - @club_list.each do |key, value|
      .checkbox
        = check_box_tag 'filter[]', key, checked(key), { class: 'filter_checkbox' }
        %label.ellipsis= value

= javascript_include_tag 'filter_submit_form'

app/views/backoffice/users/show.html.haml
.col-sm-12.profile-main.tab-content
  #general
    .column-title= "User #{@user.name}"
    %table.table.table-striped
      %tr
        %th= t('backoffice.users_page.first_name')
        %td= @user.first_name
      %tr
        %th= t('backoffice.users_page.last_name')
        %td= @user.last_name
      %tr
        %th= t('backoffice.role')
        %td= @user.role
      %tr
        %th= t('backoffice.club')
        %td= @user.club.name if @user.club.present?

    =link_to t('backoffice.edit'), edit_backoffice_user_path, class: 'btn btn-primary pull-right'

app/views/layouts/backoffice.html.haml
!!!
%html{ lang: I18n.locale }
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Clubsite
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = yield :javascripts
  %body
    = link_to 'Skip to main content', '#content', class: 'sr-only sr-only-focusable'
    %nav#header.navbar.navbar-default.navbar-inverse
      .container
        .navbar-header
          %button{ class: 'navbar-toggle collapsed', data: { toggle: 'collapse',  target: '#navbar-menu-collapsed', :'aria-expanded' => 'false' } }
            = fa 'fa-reorder fa-no-margin'
          = link_to "Clubsite", root_path, class: 'navbar-brand'

        #navbar-menu.navbar-collapse.navbar-left.hidden-xs
          %ul.nav.navbar-nav
            %li= link_to 'Clubs', backoffice_clubs_path
            %li= link_to 'Users', backoffice_users_path

        #navbar-menu-profile.navbar-collapse.navbar-right.hidden-xs
          %ul.nav.navbar-nav
            %li.dropdown
              = link_to "#", class: 'dropdown-toggle profile-link', data: { toggle: 'dropdown', role: 'button', 'aria-haspopup': true, 'aria-expanded': false } do
                = "Hi, #{current_user.name}"
                = image_tag(get_avatar(current_user.avatar), alt: '', class: 'circle-profile-img')
              %ul.dropdown-menu
                %li= link_to 'Logout', sign_out_path
        #navbar-menu-collapsed.navbar-collapse.collapse.navbar-right
          %ul.nav.navbar-nav.visible-xs
            %li= link_to 'Clubs', backoffice_clubs_path
            %li= link_to 'Users', backoffice_users_path
            %li= link_to 'Logout', sign_out_path

    - flash.each do |name, msg|
      = branded_alert(name.to_sym, msg)
    .container
      = yield